name: 'Storybook'
description: 'Run Storybook and upload results to Google Cloud Storage'
inputs:
  percy-token:
    description: 'Token for Percy'
    required: true
  skip-percy:
    description: 'Whether or not to skip Percy - if skipped build still runs and preview url is still generated'
    required: false
outputs:
  preview-url:
    description: 'URL of Storybook Preview'
    value: ${{ steps.upload.outputs.preview-url }}
runs:
  using: 'composite'
  steps:
    - name: Build Storybook
      run: yarn storybook:build
      shell: bash

    - name: Percy Visual Testing
      if: inputs.skip-percy != 'true'
      env:
        PERCY_TOKEN: ${{ inputs.percy-token }}
      run: yarn percy
      shell: bash

    - name: Retrieve PR Number
      shell: bash
      run: |
        if [ "$GITHUB_EVENT_NAME" = "merge_group" ]; then
          echo "Running in Merge Queue!"
          temp_name=${GITHUB_REF_NAME#gh-readonly-queue/main/pr-}
          pr_num="${temp_name%-*}"
        else
          echo "Not running in Merge Queue!"
          pr_num="${{ github.event.pull_request.number }}"
        fi
        echo "PR Number: $pr_num"
        echo "PR_NUM=${pr_num}" >> $GITHUB_ENV

    - name: Upload Storybook preview
      env:
        REPO_NAME: ${{ github.event.repository.name }}
      shell: bash
      id: upload
      run: |
        ls $GITHUB_WORKSPACE/docs-dist || echo "docs-dist is currently empty"
        bucket=side-plat-tools-public
        folderPath=storybook-previews/$REPO_NAME/$PR_NUM
        echo "Uploading storybook preview to Cloud Storage path \"$bucket/$folderPath\""
        gsutil -m cp -r $GITHUB_WORKSPACE/docs-dist/** gs://$bucket/$folderPath
        echo ""
        echo "Successfully uploaded Storybook preview to Cloud Storage"
        echo "preview-url=https://tools.stage-preview-lb.sideinc.dev/$folderPath/index.html" >> $GITHUB_OUTPUT
