name: 'CI Analytics'
description: 'Send CI Analytics data to DW'
inputs:
  MATRIX_NAME:
    description: 'Current matrix variable name (for parallel jobs only)'
    default: ''
    required: false
  MATRIX_VALUE:
    description: 'Current matrix variable value (for parallel jobs only)'
    default: ''
    required: false
  RESULT:
    description: 'Result of the job (failure/success).'
    required: true
  CI_SERVICE_ACCOUNT:
    description: 'Service account used for BQ access'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Get CI analytics details
      shell: bash
      if: always()
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        jobs=$(gh api --paginate /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}/jobs)
        echo "Jobs list: $jobs"
        job=$(echo $jobs | jq -r '.jobs[] | select(.runner_name=="${{ runner.name }}")' )
        job_id=$(echo $job | jq -r '.id')
        job_created_at=$(echo $job | jq -r '.created_at' | awk -F'Z' '{print $1}')
        job_started_at=$(echo $job | jq -r '.started_at' | awk -F'Z' '{print $1}')
        completed_at=$(date '+%Y-%m-%dT%H:%M:%S')
        job_link="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/$job_id"
        echo "JOB_LINK=$job_link" >> $GITHUB_ENV
        echo "CREATED_AT=$job_created_at" >> $GITHUB_ENV
        echo "STARTED_AT=$job_started_at" >> $GITHUB_ENV
        echo "COMPLETED_AT=$completed_at" >> $GITHUB_ENV

    - name: Cloud SDK Auth
      uses: google-github-actions/auth@v3
      with:
        project_id: side-dw
        credentials_json: ${{ inputs.CI_SERVICE_ACCOUNT }}
        # cleanup_credentials is set to false to avoid issues when two auth are happening within the same workflow. 
        # No impact expected because the entire workspace is cleaned up at the end of a job.
        # TODO: We should understand why it has been failing for some of our repo while it shouldn't have according to the auth action implementation. If we're able to, let's re-enable credentials cleanup as a good practice.
        cleanup_credentials: false

    - uses: reside-eng/workflow-ci-analytics-action@v1
      if: always()
      with:
        project_id: side-dw
        dataset: github
        table: ci_analytics
        matrix_name: ${{ inputs.MATRIX_NAME }}
        matrix_value: ${{ inputs.MATRIX_VALUE }}
        result: ${{ inputs.RESULT }}
        created_at: ${{ env.CREATED_AT }}
        started_at: ${{ env.STARTED_AT }}
        completed_at: ${{ env.COMPLETED_AT }}
        draft: ${{ github.event_name != 'pull_request' && 'false' || github.event.pull_request.draft }}
        job_link: ${{ env.JOB_LINK }}
        triggering_actor: ${{ github.triggering_actor }}
        run_attempt: ${{ github.run_attempt }}
        head_ref:  ${{ github.head_ref }}
        base_ref: ${{ github.base_ref }}
        runner_type: ${{ runner.environment }}
        runner_name: ${{ runner.name }}