name: 'Previews Comment'
description: 'Comment preview urls in Github PR'
inputs:
  storybook-preview-url:
    description: 'Preview url for Storybook'
    required: false
  playwright-preview-url:
    description: 'Preview url for Storybook'
    required: false
runs:
  using: "composite"
  steps:
    - name: Retrieve PR Number
      shell: bash
      run: |
        if [ "$GITHUB_EVENT_NAME" = "merge_group" ]; then
          echo "Running in Merge Queue!"
          temp_name=${GITHUB_REF_NAME#gh-readonly-queue/main/pr-}
          pr_num="${temp_name%-*}"
        else
          echo "Not running in Merge Queue!"
          pr_num="${{ github.event.pull_request.number }}"
        fi
        echo "PR Number: $pr_num"
        echo "PR_NUM=${pr_num}" >> $GITHUB_ENV

    - name: Find preview comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ env.PR_NUM }}
        comment-author: 'github-actions[bot]'
        body-includes: Preview Links

    - name: Format comments
      shell: bash
      env:
        STORYBOOK_PREVIEW_URL: ${{ inputs.storybook-preview-url }}
        PLAYWRIGHT_PREVIEW_URL: ${{ inputs.playwright-preview-url }}
      run: |
        if [ "$STORYBOOK_PREVIEW_URL" != "" ]; then
          echo "STORYBOOK_PREVIEW_COLUMN_HEADER=<th>Storybook</th>" >> $GITHUB_ENV
          echo "STORYBOOK_PREVIEW_COLUMN=<td><a href=\"$STORYBOOK_PREVIEW_URL\">🔗 Storybook Preview</a></td>" >> $GITHUB_ENV
        fi
        if [ "$PLAYWRIGHT_PREVIEW_URL" != "" ]; then
          echo "PLAYWRIGHT_PREVIEW_COLUMN_HEADER=<th>Playwright</th>" >> $GITHUB_ENV
          echo "PLAYWRIGHT_PREVIEW_COLUMN=<td><a href=\"$PLAYWRIGHT_PREVIEW_URL\">🔗 Playwright Preview</a></td>" >> $GITHUB_ENV
        fi

    - name: Comment preview links
      uses: peter-evans/create-or-update-comment@v2.1.1
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ env.PR_NUM }}
        body: |
          <table>
            <!-- Preview Links Comment Anchor -->
            <tr>
              <th>Tool</th>
              ${{ env.STORYBOOK_PREVIEW_COLUMN_HEADER }}
              ${{ env.PLAYWRIGHT_PREVIEW_COLUMN_HEADER }}
            </tr>
            <tr>
              <td>Preview Link</td>
              ${{ env.STORYBOOK_PREVIEW_COLUMN }}
              ${{ env.PLAYWRIGHT_PREVIEW_COLUMN }}
            </tr>
          </table>
        edit-mode: replace
