name: 'Previews Comment'
description: 'Comment preview urls in Github PR'
inputs:
  storybook-preview-url:
    description: 'Preview url for Storybook'
    required: true
  playwright-preview-url:
    description: 'Preview url for Storybook'
    required: true
runs:
  using: "composite"
  steps:
    - name: Find preview comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Preview Links

    - name: Format comments
      shell: bash
      env:
        STORYBOOK_PREVIEW_URL: ${{ inputs.storybook-preview-url }}
        PLAYWRIGHT_PREVIEW_URL: ${{ inputs.playwright-preview-url }}
      run: |
        echo "STORYBOOK_PREVIEW_COLUMN_HEADER=<th colspan=\"2\">Storybook Preview Link</th>" >> $GITHUB_ENV
        echo "STORYBOOK_PREVIEW_COLUMN=<td><a href=\"$STORYBOOK_PREVIEW_URL\">🔗 Storybook Preview</a></td>" >> $GITHUB_ENV
        echo "PLAYWRIGHT_PREVIEW_COLUMN_HEADER=<th colspan=\"2\">Playwright Preview Link</th>" >> $GITHUB_ENV
        echo "PLAYWRIGHT_PREVIEW_COLUMN=<td><a href=\"$PLAYWRIGHT_PREVIEW_URL\">🔗 Playwright Preview</a></td>" >> $GITHUB_ENV

    - name: Comment preview links
      uses: peter-evans/create-or-update-comment@v2.1.1
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          <table>
            <!-- Preview Links Comment Anchor -->
            <tr>
              ${{ env.STORYBOOK_PREVIEW_COLUMN_HEADER }}
              ${{ env.PLAYWRIGHT_PREVIEW_COLUMN_HEADER }}
            </tr>
            <tr>
              ${{ env.STORYBOOK_PREVIEW_COLUMN }}
              ${{ env.PLAYWRIGHT_PREVIEW_COLUMN }}
            </tr>
          </table>
        edit-mode: replace
