name: 'Playwright'
description: 'Run Playwright and upload results to Google Cloud Storage'
inputs:
  chromium-version:
    description: 'Chromium version to use for playwright tests'
    required: false
    default: '111.0.5563.146-1'
  service-account:
    description: 'Service account for authenticating Google for Cloud Storage Upload'
    required: true
outputs:
  preview-url:
    description: 'URL of Playwright Preview'
    value: ${{ steps.upload.outputs.playwright-preview-url }}
runs:
  using: 'composite'
  steps:
    - name: Install chromium
      env:
        VERSION: ${{ inputs.chromium-version }}
      run: |
        wget -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_111.0.5563.146-1_amd64.deb
        sudo apt install -yq /tmp/chrome.deb

        chromium-browser --version
        whereis chromium
      shell: bash

    - name: Install Base Fonts
      run: |
        sudo apt install fonts-noto-color-emoji \
          fonts-unifont \
          libfontconfig1 \
          libfreetype6 \
          xfonts-cyrillic \
          xfonts-scalable \
          fonts-liberation \
          fonts-ipafont-gothic \
          fonts-wqy-zenhei \
          fonts-tlwg-loma-otf \
          fonts-freefont-ttf
      shell: bash

    - name: Install Google Fonts
      run: |
        wget -O Inter.zip https://fonts.google.com/download?family=Inter
        unzip -d Inter/ Inter.zip
        mv Inter /usr/share/fonts/
        fc-cache -fv
      shell: bash

    # Ubuntu installs chrome with snap, so the fonts need to be linked
    # - name: Link system fonts
    #   run: |
    #     mkdir -p ~/snap/chromium/current/.config/fontconfig
    #     cat >> ~/snap/chromium/current/.config/fontconfig/fonts.conf << EOF
    #     <fontconfig>
    #       <include>/etc/fonts/conf.d</include>
    #     </fontconfig>
    #     EOF
    #   shell: bash

    - name: Run integration tests
      shell: bash
      run: yarn test:integration

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright-report

    - name: Upload Playwright preview
      # Run even if integration tests fail to upload failure results
      if: ${{ always() }}
      env:
        PR_NUM: ${{ github.event.pull_request.number }}
        REPO_NAME: ${{ github.event.repository.name }}
      shell: bash
      id: upload
      run: |
        ls $GITHUB_WORKSPACE/playwright-report || echo "playwright-report is currently empty"
        bucket=side-plat-tools-public
        folderPath=playwright-previews/$REPO_NAME/$PR_NUM
        echo "Uploading playwright preview to Cloud Storage path \"$bucket/$folderPath\""
        gsutil -m cp $GITHUB_WORKSPACE/playwright-report/** gs://$bucket/$folderPath
        echo ""
        echo "Successfully uploaded playwright preview to Cloud Storage"
        echo "playwright-preview-url=https://tools.stage-preview-lb.sideinc.dev/$folderPath/index.html" >> $GITHUB_OUTPUT
