name: 'Playwright'
description: 'Run Playwright and upload results to Google Cloud Storage'
inputs:
  service-account:
    description: 'Service account for authenticating Google for Cloud Storage Upload'
    required: true
outputs:
  preview-url:
    description: 'URL of Playwright Preview'
    value: ${{ steps.upload.outputs.playwright-preview-url }}
runs:
  using: 'composite'
  steps:
    - name: Install chromium
      run: npx playwright install --with-deps chromium
      shell: bash

    - name: Install Google Fonts
      run: |
        wget -O Inter.zip https://fonts.google.com/download?family=Inter
        echo "Inter Zip file downloaded, unzipping"
        unzip -d Inter/ Inter.zip
        echo "Inter font file unzipped, moving"
        mv Inter /usr/share/fonts/
        echo "Inter font file moved, building to cache"
        fc-cache -fv
        echo "Inter font built to cache"
      shell: bash

    - name: Run integration tests
      shell: bash
      run: yarn test:integration

    - name: Retrieve PR Number
      shell: bash
      run: |
        if [ "$GITHUB_EVENT_NAME" = "merge_group" ]; then
          echo "Running in Merge Queue!"
          temp_name=${GITHUB_REF_NAME#gh-readonly-queue/main/pr-}
          pr_num="${temp_name%-*}"
        else
          echo "Not running in Merge Queue!"
          pr_num="${{ github.event.pull_request.number }}"
        fi
        echo "PR Number: $pr_num"
        echo "PR_NUM=${pr_num}" >> $GITHUB_ENV

    - name: Upload Playwright preview
      # Run even if integration tests fail to upload failure results
      if: always()
      env:
        REPO_NAME: ${{ github.event.repository.name }}
      shell: bash
      id: upload
      run: |
        ls $GITHUB_WORKSPACE/playwright-report || echo "playwright-report is currently empty"
        bucket=side-plat-tools-public
        folderPath=playwright-previews/$REPO_NAME/$PR_NUM
        echo "Uploading playwright preview to Cloud Storage path \"$bucket/$folderPath\""
        gsutil -m cp -r $GITHUB_WORKSPACE/playwright-report/** gs://$bucket/$folderPath
        echo ""
        echo "Successfully uploaded playwright preview to Cloud Storage"
        echo "playwright-preview-url=https://tools.stage-preview-lb.sideinc.dev/$folderPath/index.html" >> $GITHUB_OUTPUT
